### ISSUE TITLE
Více včel na sobě

### ISSUE THREAD

**Issue by dejdy** [cvut/beeclust#2]
Mám otázku - je možné mít na jedné pozici víc včel? Například když se potkají a obě se zastaví?

**Comment by hroncok** [comment]
Ne. Když se potkají, zastaví se předtím, než na sebe vlezou.



|   |   |   |   |   |
|---|---|---|---|---|
| 1 | :bee: :arrow_right:   |   |   | :arrow_left: :bee:  |
| 2 | | :bee: :arrow_right:  | :arrow_left: :bee:  | |
| 3 | | :bee: :question:  | :question:  :bee:  | |

**Comment by hroncok** [comment]
Jedna z nich na něj vleze (ta co se zpracovává dřív), ta druhá do ní narazí.

**Comment by dejdy** [comment]
Ok, tak to je tím pádem jednoduché. Díky.

**Comment by dejdy** [comment]
A ještě jeden dotaz - pokud se mění směr pohybu včely vlivem p_change_dir, pak včela v rámci jednoho tiku pouze změní směr (a nikam se nepohne), nebo změní směr a rovnou se posune o jedno políčko v novém směru?

**Comment by hroncok** [comment]
změní směr a rovnou se posune o jedno políčko v novém směru
