### ISSUE TITLE
Speedup referencni cas

### ISSUE THREAD

**Issue by EnyMan** [cvut/beeclust#5]
Chtel bych se zeptat jestli by neslo zverejnit na jakem HW bylo referencni reseni testovano? Aby pak slo odhadnout jak je na tom nase reseni.

**Comment by hroncok** [comment]
Tohle je můj:

 * **Architektura:**          x86_64
 * **Operační režimy CPU:** 32-bit, 64-bit (použit 64-bit)
 * **Pořadí bajtů:**          Little Endian
 * **Počet CPU:**             4 (referenční řešení je v jednom vlákně, paralelizace není podstatou této úlohy)
 * **Vláken na jádro:**       2 (dtto)
 * **Uzly NUMA:**             1
 * **Výrobce:**            Intel
 * **Rodina CPU:**            6
 * **Model:**                 61
 * **Název modelu:**          Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
 * **Stepping:**              4
 * **CPU MHz:**               1496.614
 * **CPU max. MHz:**          3200,0000
 * **CPU min. MHz:**          500,0000
 * **BogoMIPS:**              5187.64
 * **L1d keš:**               32K
 * **L1i keš:**               32K
 * **L2 keš:**                256K
 * **L3 keš:**                4096K
 * **CPU NUMA uzlu 0:**       0-3
 * **Operační systém:** Fedora 29
 * **Kernel:** 4.18.16

```console
$ python -m pytest tests -k speed
...
3 passed, 71 deselected in 10.23 seconds
3 passed, 71 deselected in 10.52 seconds
3 passed, 71 deselected in 10.36 seconds
3 passed, 71 deselected in 10.32 seconds
3 passed, 71 deselected in 10.42 seconds
3 passed, 71 deselected in 10.16 seconds
3 passed, 71 deselected in 9.99 seconds
3 passed, 71 deselected in 10.26 seconds
3 passed, 71 deselected in 10.37 seconds
3 passed, 71 deselected in 11.44 seconds
```

**Comment by hroncok** [comment]
@MarekSuchanek teď ty prosím ;)

**Comment by MarekSuchanek** [comment]
Můj Acer Aspire V3-371-54SU:

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
Stepping:            4
CPU MHz:             1794.344
CPU max MHz:         3100.0000
CPU min MHz:         500.0000
BogoMIPS:            5387.62
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
```

běhy:

```
python -m pytest tests -k speed  10.19s user 0.99s system 101% cpu 11.064 total
python -m pytest tests -k speed  9.95s user 0.99s system 102% cpu 10.704 total
python -m pytest tests -k speed  10.19s user 1.06s system 101% cpu 11.055 total
python -m pytest tests -k speed  10.21s user 1.01s system 102% cpu 10.987 total
python -m pytest tests -k speed  10.58s user 0.99s system 100% cpu 11.515 total
```
