### ISSUE TITLE
speedup: cdef class BeeClust

### ISSUE THREAD

**Issue by tstdin** [cvut/beeclust#6]
Je v tomto případě možné (vycházím z referenčního řešení) nadefinovat třídu BeeClust jako cdef?

Vyžaduje to nadefinování proměnných třídy a problém je s proměnnou _map_. Když zkouším např.
```
cdef numpy.ndarray[numpy.int64_t, ndim=2] map
```
tak dostávám chybu _Buffer types only allowed as function local variables_.

**Comment by hroncok** [comment]
Může se nadefinovat jako object.

V každém případě je to zbytečně složitá cesta. Cdef class potřebuju, jen pokud si chci na třídě uchovávat C věci.

Zde stačí napsat v Cython pár funkcí a z patřičných metod je zavolat. Případně mít v cythonu vše a v patřičných def metodách zakouzlit s Cythonem, ale třídu nechat jako class.
