### ISSUE TITLE
speedup: problém s přesností

### ISSUE THREAD

**Issue by EnyMan** [cvut/beeclust#7]
Narazil jsem na problém s přesností. Když pustím normální testy tak projde vše až na to, když se používá `isclose` jak pythoní tak `numpy`. například `22,899999976158142` a `isclose` chce `22,9`. 

Z dokumentace pythonu má `isclose` relativní tolerancí `1e-09` takzvaně na 9 desetiných míst.

Je vidět, že to už nesplňuje první desetiné číslo, mám to nějak řešit nebo je to v rámci tolerancí?

**Comment by hroncok** [comment]
Jaké používáš floaty? Klidně tu toleranci asi můžeme zvýšit, pokud to není nějakým blbý floatem.
